sync:
  name: Sync policy to AdGuard Home
  description: Reads a JSON file of devices, applies per-tag client settings, and pushes custom rules to AdGuard Home.
  fields:
    devices_json:
      name: Devices JSON path (optional)
      description: Path to devices JSON. If omitted, uses the path from the config entry.
      example: adguard_devices.json
      required: false
      selector:
        text:
    rules_text:
      name: Custom rules (optional)
      description: If provided, these rules replace the instance's current custom rules (dynamic rules may still be appended if enabled).
      required: false
      selector:
        text: