sync:
  name: Sync policy to AdGuard Home
  description: "Apply custom rules and sync clients from a devices JSON. Can optionally scan the LAN first."
  fields:
    devices_json:
      name: Devices JSON (optional)
      description: "Path to devices JSON; defaults to the config entry value."
      required: false
      selector: { text: {} }
    rules_text:
      name: Custom rules (optional)
      description: "If provided, replaces current custom rules (dynamic rules may still be appended)."
      required: false
      selector: { text: {} }
    scan_range:
      name: Scan range (optional)
      description: "CIDR to ping & discover live devices before syncing, e.g. 10.2.0.0/24."
      required: false
      selector: { text: {} }
    auto_onboard_unknowns:
      name: Auto-onboard unknowns
      description: "If true, unknown live devices are added as Guest persistent clients."
      required: false
      selector: { boolean: {} }
    guest_group:
      name: Guest group name
      description: "Friendly group to apply for unknowns (defaults to 'guest')."
      required: false
      selector: { text: {} }

discover:
  name: Discover live devices (ping sweep + ARP) and optionally onboard as Guests
  description: "Pings a CIDR, reads ARP to find MACs, then adds persistent Guest clients for unknown devices."
  fields:
    scan_range:
      name: Scan range
      description: "CIDR to scan, e.g. 10.2.0.0/24."
      required: true
      selector: { text: {} }
    guest_group:
      name: Guest group name
      description: "Friendly group to use for presets when onboarding (default 'guest')."
      required: false
      selector: { text: {} }
    create_clients:
      name: Create clients
      description: "If true, creates Guest clients; if false, just emits discovery events."
      required: false
      selector: { boolean: {} }
