sync:
  name: Sync policy to AdGuard Home
  description: "Apply custom rules and sync clients from JSON. Optionally auto-onboard unknown devices from DHCP."
  fields:
    devices_json:
      name: Devices JSON (optional)
      description: "Path under /config, e.g. adguard_devices.json. Uses the configured default if omitted."
      required: false
      selector:
        text: {}
    rules_text:
      name: Custom rules (optional)
      description: "If provided, replaces current custom rules; dynamic rules may still be appended."
      required: false
      selector:
        text:
          multiline: true
    auto_onboard_unknowns:
      name: Auto-onboard unknowns
      description: "If on, devices seen in DHCP but not in JSON are created as Guest persistent clients."
      required: false
      selector:
        boolean: {}
    guest_group:
      name: Guest group name
      description: "Friendly group to use for presets for unknowns (default 'guest')."
      required: false
      selector:
        text: {}

discover:
  name: Discover devices from DHCP and optionally onboard as Guests
  description: "Reads AdGuard Home DHCP leases, updates existing clients to include MAC+IP, and can create Guest clients for unknowns."
  fields:
    guest_group:
      name: Guest group name
      description: "Friendly group for presets when onboarding (default 'guest')."
      required: false
      selector:
        text: {}
    create_clients:
      name: Create Guest clients
      description: "If false, just emits discovery events; if true, also adds persistent Guest clients."
      required: false
      selector:
        boolean: {}

pause:
  name: Pause filtering for specific clients
  description: "Temporarily pause filtering (and optionally Safe Browsing/Parental/blocked services) for selected clients, then auto-restore."
  fields:
    minutes:
      name: Minutes
      description: "Duration to pause (default 15)."
      required: false
      selector:
        number:
          min: 1
          max: 240
          step: 1
          mode: box
    scope:
      name: Scope
      description: "'filtering_only' disables filtering; 'all' also disables Safe Browsing, Parental and blocked services."
      required: false
      selector:
        select:
          options:
            - filtering_only
            - all
          mode: dropdown
    clients:
      name: Clients
      description: "YAML list of client names to pause (e.g. ['Apple iPhone 14','Dell Latitude Laptop'])."
      required: true
      selector:
        object: {}

block:
  name: Block clients (runtime)
  description: "Adds clients to a deny-all rule via $client=… dynamic rules."
  fields:
    clients:
      name: Clients
      description: "List of client names (exactly as in AdGuard Home)."
      required: true
      example: '["Apple iPhone 14","MacBook Pro"]'
      selector: { object: {} }
    minutes:
      name: Minutes
      description: "Optional duration; if omitted, block until manually unblocked."
      required: false
      selector: { number: { min: 1, step: 1 } }

unblock:
  name: Unblock clients (runtime)
  description: "Removes clients from the runtime deny-all rule and refreshes rules."
  fields:
    clients:
      name: Clients
      description: "List of client names."
      required: true
      example: '["Apple iPhone 14"]'
      selector: { object: {} }
