sync:
  name: Sync policy to AdGuard Home
  description: "Generates and applies custom rules, then syncs clients from a devices JSON."
  fields:
    devices_json:
      name: "Devices JSON path (optional)"
      description: "Path to devices JSON. If omitted, uses the path from the config entry."
      example: adguard_devices.json
      required: false
      selector:
        text: {}
    rules_text:
      name: "Custom rules (optional)"
      description: "If provided, replaces the current custom rules (dynamic rules may still be appended if enabled)."
      required: false
      selector:
        text: {}

pause:
  name: Pause protection for clients
  description: "Temporarily disables protection for selected clients and automatically restores it."
  fields:
    clients:
      name: "Client names"
      description: "Exact client names as shown in AdGuard Home."
      required: true
      selector:
        text: {}
    minutes:
      name: Minutes
      description: "Duration of the pause (default 15)."
      required: false
      selector:
        number:
          min: 1
          max: 240
          mode: box
          unit_of_measurement: minutes
    scope:
      name: Scope
      description: "Use 'filtering_only' to disable only filtering rules; use 'all' to also disable Browsing Security, Parental, and clear blocked services."
      required: false
      selector:
        select:
          options:
            - filtering_only
            - all
